service: indy-ingest-api

provider:
  name: aws
  runtime: go1.x
  environment:
    SUBMISSIONS_TABLE: "${self:service}-${opt:stage, self:provider.stage}-submissions"
    AUTH0_CLIENT_ID: ${file(./secrets.json):AUTH0_CLIENT_ID}
    AUTH0_CLIENT_PUBLIC_KEY: ${file(./public_key)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.SUBMISSIONS_TABLE}"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  create-submission:
    handler: bin/create_submission
    events:
      - http:
          path: submissions
          method: post
          cors: true
  list-submissions:
    handler: bin/dummy
    events:
      - http:
          path: submissions
          method: get
  get-submission:
    handler: bin/dummy
    events:
      - http:
          path: submissions/{id}
          method: get
          request:
            parameters:
              paths:
              id: true
  create-metadata:
    handler: bin/dummy
    events:
      - http:
          path: submissions/{id}/metadata
          method: post
          request:
            parameters:
              paths:
              id: true
  list-metadata:
    handler: bin/dummy
    events:
      - http:
          path: submissions/{id}/metadata
          method: get
          request:
            parameters:
              paths:
              id: true
  get-metadata:
    handler: bin/dummy
    events:
      - http:
          path: submissions/{id}/metadata/{uuid}
          method: get
          request:
            parameters:
              paths:
                id: true
                uuid: true
  validate:
    handler: bin/validate
    events:
    - http:
        path: validate
        method: post

resources:
  Resources:
    SubmissionsDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.SUBMISSIONS_TABLE}
        AttributeDefinitions:
          - AttributeName: owner
            AttributeType: S
          - AttributeName: submission_id
            AttributeType: S
        KeySchema:
          - AttributeName: owner
            KeyType: HASH
          - AttributeName: submission_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'